[package]
name = "interrupt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "18.0"
wasmtime-wasi = "0.24"
wasi-cap-std-sync = "0.24"
anyhow = "1"
